CREATE DATABASE IF NOT EXISTS reyhans_grill
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE reyhans_grill;

CREATE TABLE IF NOT EXISTS Category (
  Category_ID VARCHAR(20) PRIMARY KEY,
  Category_Name VARCHAR(100) NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP


CREATE TABLE IF NOT EXISTS Inventory_Settings (
  Setting_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  Low_Stock_Threshold INT UNSIGNED NOT NULL DEFAULT 10,
  Expiring_Soon_Days INT UNSIGNED NOT NULL DEFAULT 7,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user (
  User_ID VARCHAR(20) PRIMARY KEY,
  Username VARCHAR(50) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Item (
  Item_ID VARCHAR(20) PRIMARY KEY,
  Item_Name VARCHAR(120) NOT NULL,
  Category_ID VARCHAR(20) NOT NULL,
  Quantity_in_Stock INT UNSIGNED NOT NULL DEFAULT 0,
  Unit VARCHAR(50) NOT NULL DEFAULT 'each',
  Unit_Cost DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  Shelf_Life_Days INT UNSIGNED DEFAULT 0,
  Expiration_Date DATE,
  Status ENUM('AVAILABLE', 'LOW', 'OUT_OF_STOCK') NOT NULL DEFAULT 'AVAILABLE',
  Item_Type ENUM('MATERIAL', 'UTENSIL', 'OTHER') NOT NULL DEFAULT 'MATERIAL',
  Par_Level INT UNSIGNED DEFAULT 0,
  Reorder_Point INT UNSIGNED DEFAULT 0,
  Is_Deleted TINYINT(1) NOT NULL DEFAULT 0,
  Deleted_At TIMESTAMP NULL DEFAULT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_category FOREIGN KEY (Category_ID) REFERENCES Category (Category_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT


CREATE TABLE IF NOT EXISTS Inventory_Settings (
  Setting_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  Low_Stock_Threshold INT UNSIGNED NOT NULL DEFAULT 10,
  Expiring_Soon_Days INT UNSIGNED NOT NULL DEFAULT 7,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `usage` (
  Usage_ID VARCHAR(24) PRIMARY KEY,
  Item_ID VARCHAR(20) NOT NULL,
  Quantity_Used INT UNSIGNED NOT NULL,
  Date_Used DATE NOT NULL,
  User_ID VARCHAR(20) NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_usage_item FOREIGN KEY (Item_ID) REFERENCES Item (Item_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_usage_user FOREIGN KEY (User_ID) REFERENCES user (User_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Inventory_Usage (
  Usage_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Item_ID VARCHAR(20) NOT NULL,
  Used_Quantity INT UNSIGNED NOT NULL,
  Usage_Date DATE NOT NULL DEFAULT (CURRENT_DATE),
  Notes VARCHAR(255),
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inventory_usage_item FOREIGN KEY (Item_ID) REFERENCES Item (Item_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Material_Usage (
  Usage_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Item_ID VARCHAR(20) NOT NULL,
  Usage_Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Quantity_Used DECIMAL(10, 2) NOT NULL,
  Reason VARCHAR(100),
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_material_usage_item FOREIGN KEY (Item_ID) REFERENCES Item (Item_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Purchase (
  Purchase_ID VARCHAR(24) PRIMARY KEY,
  User_ID VARCHAR(20) NOT NULL,
  Item_ID VARCHAR(20) NOT NULL,
  Quantity_Purchased INT UNSIGNED NOT NULL,
  Purchase_Date DATE NOT NULL,
  Total_Cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_item FOREIGN KEY (Item_ID) REFERENCES Item (Item_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_purchase_user FOREIGN KEY (User_ID) REFERENCES user (User_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Report (
  Report_ID VARCHAR(40) PRIMARY KEY,
  Report_Date DATE NOT NULL,
  Total_Spent DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  Total_Used_Items INT UNSIGNED NOT NULL DEFAULT 0,
  User_ID VARCHAR(20) NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_report_user FOREIGN KEY (User_ID) REFERENCES user (User_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO Inventory_Settings (Setting_ID, Low_Stock_Threshold, Expiring_Soon_Days) VALUES
  (1, 10, 7)
ON DUPLICATE KEY UPDATE
  Low_Stock_Threshold = VALUES(Low_Stock_Threshold),
  Expiring_Soon_Days = VALUES(Expiring_Soon_Days);

INSERT INTO Category (Category_ID, Category_Name) VALUES
  ('CAT_FRUITS', 'Fruits'),
  ('CAT_VEG', 'Vegetables'),
  ('CAT_GRAINS', 'Grains'),
  ('CAT_PROTEIN', 'Protein'),
  ('CAT_DAIRY', 'Dairy'),
  ('CAT_DRINK', 'Drinks'),
  ('CAT_COOK', 'Cooking'),
  ('CAT_SERVE', 'Serving'),
  ('CAT_BAKE', 'Baking'),
  ('CAT_CUT', 'Cutlery'),
  ('CAT_STORE', 'Storage')
ON DUPLICATE KEY UPDATE Category_Name = VALUES(Category_Name);

INSERT INTO user (User_ID, Username, Password) VALUES
  ('USR_ADMIN', 'admin', '$2a$12$examplehashchangeme')
ON DUPLICATE KEY UPDATE Username = VALUES(Username), Password = VALUES(Password);
