CREATE TABLE IF NOT EXISTS Category (
  Category_ID VARCHAR(64) PRIMARY KEY,
  Category_Name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Item (
  Item_ID VARCHAR(64) PRIMARY KEY,
  Item_Name VARCHAR(255) NOT NULL,
  Category_ID VARCHAR(64),
  Quantity_In_Stock INT DEFAULT 0,
  Unit_Cost DECIMAL(10, 2) DEFAULT 0.00,
  Shelf_Life_Days INT,
  Expiration_Date DATE,
  Status VARCHAR(32) DEFAULT 'ACTIVE',
  CONSTRAINT fk_item_category
    FOREIGN KEY (Category_ID)
    REFERENCES Category (Category_ID)
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Users (
  User_ID VARCHAR(64) PRIMARY KEY,
  Username VARCHAR(64) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Purchase (
  Purchase_ID VARCHAR(64) PRIMARY KEY,
  User_ID VARCHAR(64) NOT NULL,
  Item_ID VARCHAR(64) NOT NULL,
  Quantity_Purchased INT NOT NULL,
  Purchase_Date DATE NOT NULL,
  Total_Cost DECIMAL(10, 2) NOT NULL,
  CONSTRAINT fk_purchase_user
    FOREIGN KEY (User_ID) REFERENCES Users (User_ID),
  CONSTRAINT fk_purchase_item
    FOREIGN KEY (Item_ID) REFERENCES Item (Item_ID)
);

CREATE TABLE IF NOT EXISTS Usage (
  Usage_ID VARCHAR(64) PRIMARY KEY,
  Item_ID VARCHAR(64) NOT NULL,
  Quantity_Used INT NOT NULL,
  Date_Used DATE NOT NULL,
  User_ID VARCHAR(64),
  CONSTRAINT fk_usage_item
    FOREIGN KEY (Item_ID) REFERENCES Item (Item_ID),
  CONSTRAINT fk_usage_user
    FOREIGN KEY (User_ID) REFERENCES Users (User_ID)
);

CREATE TABLE IF NOT EXISTS Report (
  Report_ID VARCHAR(64) PRIMARY KEY,
  Report_Date DATE NOT NULL,
  Total_Spent DECIMAL(10, 2) DEFAULT 0.00,
  Total_Used_Items INT DEFAULT 0,
  User_ID VARCHAR(64),
  CONSTRAINT fk_report_user
    FOREIGN KEY (User_ID) REFERENCES Users (User_ID)
);
