CREATE TABLE IF NOT EXISTS Inventory_Settings (
  Setting_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  Low_Stock_Threshold INT UNSIGNED NOT NULL DEFAULT 10,
  Expiring_Soon_Days INT UNSIGNED NOT NULL DEFAULT 7,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO Inventory_Settings (Setting_ID, Low_Stock_Threshold, Expiring_Soon_Days)
VALUES (1, 10, 7)
ON DUPLICATE KEY UPDATE
  Low_Stock_Threshold = VALUES(Low_Stock_Threshold),
  Expiring_Soon_Days = VALUES(Expiring_Soon_Days);

ALTER TABLE Item
  ADD COLUMN Low_Stock_Threshold INT UNSIGNED DEFAULT NULL AFTER Purchase_Date,
  ADD COLUMN Expiring_Soon_Days INT UNSIGNED DEFAULT NULL AFTER Low_Stock_Threshold;
