CREATE TABLE IF NOT EXISTS Material_Usage (
  Usage_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Item_ID VARCHAR(20) NOT NULL,
  Usage_Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Quantity_Used DECIMAL(10, 2) NOT NULL,
  Reason VARCHAR(100) NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_material_usage_item FOREIGN KEY (Item_ID) REFERENCES Item (Item_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
