CREATE TABLE IF NOT EXISTS Inventory_Usage (
  Usage_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Item_ID VARCHAR(20) NOT NULL,
  Used_Quantity INT UNSIGNED NOT NULL,
  Usage_Date DATE NOT NULL DEFAULT (CURRENT_DATE),
  Notes VARCHAR(255),
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inventory_usage_item FOREIGN KEY (Item_ID) REFERENCES Item (Item_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
